In [1]:
import random
import numpy as np

In [2]:
%precision 3

'%.3f'

In [3]:
n = 1000000
x = [random.random() for _ in range(n)]
y = [random.random() for _ in range(n)]

In [4]:
x[:3], y[:3]

([0.947, 0.373, 0.465], [0.859, 0.627, 0.029])

In [5]:
z = [x[i] + y[i] for i in range(n)]
z[:3]

[1.805, 1.000, 0.494]

In [6]:
%timeit [x[i] + y[i] for i in range(n)]

1 loop, best of 3: 195 ms per loop


In [9]:
xa = np.array(x)
ya = np.array(y)

In [10]:
xa[:3]

array([ 0.947,  0.373,  0.465])

In [11]:
za = xa + ya
za[:3]

array([ 1.805,  1.   ,  0.494])

In [12]:
%timeit xa + ya

100 loops, best of 3: 3.64 ms per loop


In [13]:
%timeit sum(x)
%timeit np.sum(xa)

100 loops, best of 3: 6.21 ms per loop
1000 loops, best of 3: 507 µs per loop


In [17]:
d = [abs(x[i] - y[j])
for i in range(1000) for j in range(1000)]

In [18]:
d[:3]

[0.088, 0.319, 0.917]

In [19]:
da = np.abs(xa[:1000, None] - ya[:1000])

In [20]:
da

array([[ 0.088,  0.319,  0.917, ...,  0.008,  0.925,  0.885],
       [ 0.486,  0.254,  0.344, ...,  0.581,  0.351,  0.312],
       [ 0.393,  0.162,  0.436, ...,  0.489,  0.443,  0.404],
       ..., 
       [ 0.843,  0.612,  0.014, ...,  0.939,  0.007,  0.046],
       [ 0.062,  0.293,  0.891, ...,  0.034,  0.898,  0.859],
       [ 0.102,  0.333,  0.931, ...,  0.006,  0.938,  0.899]])

In [21]:
%timeit [abs(x[i] - y[j]) for i in range(1000) for j in range(1000)]
%timeit np.abs(xa[:1000, None] - ya[:1000])

1 loop, best of 3: 241 ms per loop
100 loops, best of 3: 6.87 ms per loop
